-- Decompiled using luadec 2.2 rev:  for Lua 5.2 from https://github.com/viruscamp/luadec
-- Command line: A:\Steam\twd-definitive\scripteditor-10-31-20\definitive_lighting_improvements\WDC_pc_WalkingDead403_data\TrainTile_temp.lua 

-- params : ...
-- function num : 0 , upvalues : _ENV
require("Relighting.lua")
require("PropertyMenuTool.lua")
require("CustomSound.lua")

local kScript = "TrainTile"
local kScene = "adv_trainTile"


ModifyScene = function(sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesAFencesPowerLinesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesAFencesPowerLinesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesAFencesPowerLinesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesAGrassA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesAGrassB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesAGrassC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesAGrassD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesARocksA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesARocksB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesARocksC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesARocksD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATerrainA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATerrainB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATerrainC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATerrainD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATreeFlatsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATreeFlatsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATreeFlatsC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATreeFlatsD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATreesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATreesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATreesC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesATreesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBGrassA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBGrassB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBGrassC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBGrassD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBHouse", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBPuddles", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBRocksA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBRocksB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBRocksC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBRocksD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTerrainA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTerrainB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTerrainC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTerrainD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTreeFlatsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTreeFlatsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTreeFlatsC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTreeFlatsD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTreesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTreesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTreesC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesBTreesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCBushesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCBushesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCGrassA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCGrassB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCGrassC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCGrassD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCRocksA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCRocksB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCRocksC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCRocksD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCSignsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTerrainA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTerrainB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTerrainC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTerrainD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTreeFlatsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTreeFlatsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTreeFlatsC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTreeFlatsD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTreesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTreesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTreesC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCTreesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDFencesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDFencesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDGrassA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDGrassB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDGrassC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDGrassD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDHouse", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDRocksA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDRocksB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDRocksC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDRocksD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDSignsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTerrainA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTerrainB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTerrainC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTerrainD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreeFlatsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreeFlatsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreeFlatsC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreeFlatsD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreesC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreesE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesDTreesF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesEFencesPowerLinesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesEFencesPowerLinesC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesEFencesPowerLinesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesEGrassA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesEGrassB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesEGrassC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesEGrassD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesEHouse", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesERocksA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesERocksB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesERocksC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesERocksD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETerrainA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETerrainB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETerrainC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETerrainD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreeFlatsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreeFlatsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreeFlatsC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreeFlatsD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreesC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreesE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesETreesF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFBushesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFBushesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFBushesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFBushesE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFBushesF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFFencesSignsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFFencesSignsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFFencesSignsC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFFencesSignsE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFFencesSignsF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFGrassA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFGrassB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFGrassC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFGrassD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFGrassE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFGrassF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFHouse", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFRocksA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFRocksB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFRocksC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFRocksD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFRocksE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFRocksF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTerrainA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTerrainB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTerrainC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTerrainD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTerrainE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTerrainF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreeFlatsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreeFlatsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreeFlatsC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreeFlatsD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreeFlatsE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreeFlatsF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreesC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreesE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesFTreesF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGBushesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGBushesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGBushesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGBushesE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGBushesF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGFencesSignsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGFencesSignsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGFencesSignsD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGFencesSignsE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGFencesSignsF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGGrassA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGGrassB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGGrassC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGGrassD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGGrassE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGGrassF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGRocksA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGRocksB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGRocksC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGRocksD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGRocksE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGRocksF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTerrainA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTerrainB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTerrainC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTerrainD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTerrainE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTerrainF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreeFlatsA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreeFlatsB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreeFlatsC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreeFlatsD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreeFlatsE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreeFlatsF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreesA", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreesB", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreesC", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreesD", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreesE", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesGTreesF", sceneObj)
    Custom_RemoveAgent("adv_roadTile_meshesCGrassOpening", sceneObj)

    local sunColor     = RGBColor(255, 153, 35, 255)
    local ambientColor = RGBColor(72,168,255, 255)
    local skyColor     = RGBColor(24, 99, 205, 255)
    --local fogColor     = Desaturate_RGBColor(skyColor, 0.45)
    skyColor = Desaturate_RGBColor(skyColor, 0.2)
    ambientColor = Desaturate_RGBColor(ambientColor, 0.35)
    sunColor = Desaturate_RGBColor(sunColor, 0.01)
    
    --enviorment module (fog)
    --local envModule       = AgentFindInScene("module_environment_fog", sceneObj)
    --local envModule_props = AgentGetRuntimeProperties(envModule)
    --customSetPropertyColor(envModule_props, "5416356241638078242", sunColor)

    --camera
    --local sceneCamera = SceneGetCamera(sceneObj)
    --local sceneCamera_props = AgentGetRuntimeProperties(sceneCamera)
    --customSetProperty(sceneCamera_props, "550511701480871091", 25.5) --no clue
    
    --lightprobe
    --local probeModule            = AgentFindInScene("module_lightprobe", sceneObj)
    --local probeModule_props = AgentGetRuntimeProperties(probeModule)
    --customSetProperty(probeModule_props, "1025426863444100460", 25.5) --no clue
    
    --sky
    local sky_amb = AgentFindInScene("light_SKY_amb", sceneObj)
    local sky_amb_props = AgentGetRuntimeProperties(sky_amb)
    PropertySet(sky_amb_props, "EnvLight - Color", skyColor)
    PropertySet(sky_amb_props, "EnvLight - Intensity", 0.6)
    
    --ambient
    local amb = AgentFindInScene("light_ENV_ambFill", sceneObj)
    local amb_props = AgentGetRuntimeProperties(amb)
    PropertySet(amb_props, "EnvLight - Color", ambientColor)
    PropertySet(amb_props, "EnvLight - Intensity", 0.35)
    PropertySet(amb_props, "EnvLight - Intensity Specular", 1)
    
    --sun
    local mainSun = AgentFindInScene("light_ENV_D_SunKey", sceneObj)
    local mainSun_props = AgentGetRuntimeProperties(mainSun)
    PropertySet(mainSun_props, "EnvLight - Color", sunColor)
    PropertySet(mainSun_props, "EnvLight - Intensity", 8)
    PropertySet(mainSun_props, "EnvLight - Intensity Specular", 1)
    PropertySet(mainSun_props, "EnvLight - HBAO Participation Type", 1)
    
    ModifyAgentTransformation_Rotation(mainSun, Vector(2, -90, 0))
    
    --sun ambient
    local sunAmb = AgentCreate("sunAmb", mainSun_props, Vector(0,0,0), AgentGetRot(mainSun), sceneObj, false, false)
    local sunAmb_props = AgentGetRuntimeProperties(sunAmb)
    PropertySet(sunAmb_props, "EnvLight - Wrap", 1)
    PropertySet(sunAmb_props, "EnvLight - Intensity", 1.0)
    PropertySet(sunAmb_props, "EnvLight - Type", 4)
    
    --scene post process
    local sceneAgent = AgentFindInScene("adv_trainTile.scene", sceneObj)
    local sceneAgent_props = AgentGetRuntimeProperties(sceneAgent)
    PropertySet(sceneAgent_props, "HBAO Intensity", 1)
    PropertySet(sceneAgent_props, "HBAO Radius", 0.5)
    PropertySet(sceneAgent_props, "HBAO Hemisphere Bias", 0.1)
    PropertySet(sceneAgent_props, "Generate NPR Lines", false)
    PropertySet(sceneAgent_props, "FX Sharp Shadows Enabled", true)
    PropertySet(sceneAgent_props, "FX Tonemap Enabled", true)
    PropertySet(sceneAgent_props, "FX Tonemap DOF Enabled", true)
    PropertySet(sceneAgent_props, "FX Tonemap White Point", 5)
    PropertySet(sceneAgent_props, "FX Tonemap Filmic Shoulder Intensity", 0.5)
    PropertySet(sceneAgent_props, "FX Tonemap Filmic Toe Intensity", 1)
    PropertySet(sceneAgent_props, "FX Bloom Intensity", 0.5)
    PropertySet(sceneAgent_props, "FX Bloom Threshold", -0.35)
    PropertySet(sceneAgent_props, "FX TAA Weight", 0)

    RemovingAllLightingRigs(sceneObj)
    RemoveNPR_OutlineOnAllAgents(sceneObj)
end


TrainTile = function()
  -- function num : 0_0 , upvalues : _ENV
  Episode_SetClemButton()
  
  ModifyScene(kScene)
  Devtools_Init(kScene)
end

Game_SceneOpen(kScene, kScript)

